language: php
before_script:
    - wget http://getcomposer.org/composer.phar
	- php composer.phar install --dev
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm
matrix:
    allow_failures:
        - php: hhvm

script: phpunit

after_script:
    - php vendor/bin/coveralls -v